import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, justifyContent: 'center', padding: 20, backgroundColor: '#f4f6f9' },
  mainContainer: { flex: 1, backgroundColor: '#f4f6f9', paddingTop: 40 },
  tabContent: { flex: 1, padding: 20 },
  centerContent: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  title: { fontSize: 28, fontWeight: 'bold', textAlign: 'center', marginBottom: 30, color: '#2c3e50' },
  subtitle: { fontSize: 18, textAlign: 'center', marginBottom: 20 },
  input: { backgroundColor: '#fff', padding: 15, borderRadius: 10, marginBottom: 15, fontSize: 16 },
  button: { backgroundColor: '#3498db', padding: 15, borderRadius: 10, alignItems: 'center', marginBottom: 15 },
  logoutBtn: { backgroundColor: '#e74c3c' },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  walletCard: { backgroundColor: '#fff', padding: 20, borderRadius: 15, alignItems: 'center', marginBottom: 30, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 10, elevation: 5, width: '100%' },
  walletLabel: { color: '#7f8c8d', fontSize: 14, marginBottom: 5 },
  walletAmount: { fontSize: 32, fontWeight: 'bold', color: '#2ecc71' },
  walletHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 15, width: '100%', borderBottomWidth: 1, borderBottomColor: '#f0f0f0', paddingBottom: 10 },
  walletTitle: { fontSize: 18, fontWeight: 'bold', color: '#2c3e50', marginLeft: 10 },
  walletActions: { flexDirection: 'row', justifyContent: 'space-around', width: '100%', marginTop: 20, paddingTop: 15, borderTopWidth: 1, borderTopColor: '#f0f0f0' },
  walletActionButton: { alignItems: 'center', flex: 1 },
  walletActionIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#2ecc71', justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  walletActionText: { fontSize: 13, color: '#34495e', fontWeight: '500' },
  overlay: { position: 'absolute', bottom: 50, left: 20, right: 20, backgroundColor: 'rgba(0,0,0,0.7)', padding: 20, borderRadius: 15, alignItems: 'center' },
  scanText: { color: '#fff', fontSize: 16, marginBottom: 15, textAlign: 'center' },
  
  headerContainer: { alignItems: 'center', marginBottom: 35 },
  logoContainer: { width: 90, height: 90, backgroundColor: '#e1f0fa', borderRadius: 45, justifyContent: 'center', alignItems: 'center', marginBottom: 15, shadowColor: '#3498db', shadowOpacity: 0.2, shadowRadius: 10, elevation: 5 },
  mainTitle: { fontSize: 32, fontWeight: 'bold', color: '#2c3e50', marginBottom: 8 },
  subTitleText: { fontSize: 16, color: '#7f8c8d' },
  optionsRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 25, paddingHorizontal: 5 },
  checkboxContainer: { flexDirection: 'row', alignItems: 'center' },
  checkbox: { width: 18, height: 18, borderWidth: 1.5, borderColor: '#3498db', borderRadius: 4, marginRight: 8, backgroundColor: '#fff' },
  checkboxChecked: { backgroundColor: '#3498db' },
  optionText: { color: '#34495e', fontSize: 14 },
  forgotPasswordText: { color: '#e74c3c', fontSize: 14, fontWeight: '600' },
  registerRow: { flexDirection: 'row', justifyContent: 'center', marginTop: 30 },
  registerText: { color: '#7f8c8d', fontSize: 15 },
  registerLink: { color: '#3498db', fontSize: 15, fontWeight: 'bold' },
  tabBar: { flexDirection: 'row', backgroundColor: '#fff', borderTopWidth: 1, borderTopColor: '#e0e0e0', paddingBottom: 20, paddingTop: 10 },
  tabItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  tabText: { fontSize: 12, color: '#7f8c8d', marginTop: 4 },
  tabTextActive: { color: '#3498db', fontWeight: 'bold' },
  
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#2c3e50', marginTop: 20, marginBottom: 15 },
  stationCard: { flexDirection: 'row', backgroundColor: '#fff', padding: 15, borderRadius: 12, marginBottom: 15, alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 5, elevation: 2 },
  stationIcon: { width: 50, height: 50, backgroundColor: '#e1f0fa', borderRadius: 25, justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  stationInfo: { flex: 1 },
  stationName: { fontSize: 16, fontWeight: 'bold', color: '#2c3e50', marginBottom: 4 },
  stationLocation: { fontSize: 13, color: '#7f8c8d' },
  stationStatus: { paddingLeft: 10 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12, fontSize: 12, fontWeight: 'bold', overflow: 'hidden' },
  statusOnline: { backgroundColor: '#e8f8f5', color: '#2ecc71' },
  statusOffline: { backgroundColor: '#fdedec', color: '#e74c3c' },
  backButton: { flexDirection: 'row', alignItems: 'center', marginBottom: 15, paddingVertical: 5 },
  backButtonText: { fontSize: 16, color: '#34495e', marginLeft: 8, fontWeight: '500' },
  stationDetailHeader: { alignItems: 'center', backgroundColor: '#fff', padding: 20, borderRadius: 15, marginBottom: 20, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 5, elevation: 2 },
  detailTitle: { fontSize: 20, fontWeight: 'bold', color: '#2c3e50', marginBottom: 5 },
  detailLocation: { fontSize: 14, color: '#7f8c8d', marginBottom: 10, textAlign: 'center' },
  detailPrice: { fontSize: 15, color: '#e67e22', fontWeight: 'bold' },
  outletsContainer: { flexDirection: 'row', justifyContent: 'space-between' },
  outletCard: { flex: 1, backgroundColor: '#fff', padding: 20, borderRadius: 15, alignItems: 'center', marginHorizontal: 5, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 5, elevation: 2 },
  outletName: { fontSize: 16, fontWeight: 'bold', color: '#2c3e50', marginBottom: 5 },
  outletStatus: { fontSize: 13, color: '#2ecc71' }
});