[platformio]
; Chọn môi trường mặc định (Có thể đổi qua lại bằng thanh công cụ ở dưới đáy VSCode)
default_envs = station 

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; --- MÔI TRƯỜNG DÀNH CHO BỘ TRUNG TÂM (GATEWAY) ---
[env:gateway]
build_src_filter = +<gateway/> -<station/>
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
    emelianov/modbus-esp8266@^4.1.0  ; Thư viện Modbus Master

; --- MÔI TRƯỜNG DÀNH CHO CÁC TỦ SẠC (STATION) ---
[env:station]
build_src_filter = +<station/> -<gateway/>
lib_deps = 
	adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
	adafruit/Adafruit GFX Library
	adafruit/Adafruit ST7735 and ST7789 Library
	ricmoo/QRCode@^0.0.1
	mandulaj/PZEM-004T-v30@^1.1.2
    emelianov/modbus-esp8266@^4.1.0  ; Thư viện Modbus Slave
